### ISSUE TITLE
[Feature Request][Spark][WIP] Metadata only queries - Umbrella issue

### ISSUE THREAD

**Issue by felipepessoto** [delta-io/delta#2589]
#### Which Delta project/connector is this regarding?
- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Overview

This is the umbrella issue for metadata only queries.

### Motivation

Running queries on metadata only has huge performance improvement, up to 100x in some cases.

### Further details
Delta Log provides the following information:

[Stats](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#per-file-statistics) (optional):
- numRecords
- minValues
- maxValues
- nullValues

[PartitionValues](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#partition-value-serialization):
- The actual value

## Project Plan
| ID | Task description | Issue | PR | Status | Author |
|:---:|:---:|---|:---:|:---:|---|
| 1 | SELECT COUNT(*) FROM Table | https://github.com/delta-io/delta/issues/1192 | https://github.com/delta-io/delta/pull/1377 | Done | @felipepessoto |
| 2 | SELECT MIN(X), MAX(X) FROM Table | https://github.com/delta-io/delta/issues/2092 | https://github.com/delta-io/delta/pull/1525 | Done | @felipepessoto |
| 3 | SELECT COUNT(*), MIN(X), MAX(X) FROM table WHERE partition_column = 1 | https://github.com/delta-io/delta/issues/1916 |  |  |  |
| 4 | SELECT partition_column, COUNT(*) FROM table GROUP BY partition_column |  |  |  |  |
| 5 | SELECT DISTINCT partition_column FROM table |  |  |  |  |
| 6 |  |  |  |  |  |
| 7 |  |  |  |  |  |
| 8 |  |  |  |  |  |
| 9 |  |  |  |  |  |

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [X] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by ItaiYaffeAkamai** [comment]
Thanks, @felipepessoto, for unifying all those under a single umbrella issue - I think it's really beneficial!

**Comment by felipepessoto** [comment]
In #1525 we left two comments open:

https://github.com/delta-io/delta/pull/1525#discussion_r1439773215
![image](https://github.com/delta-io/delta/assets/1336227/a4de17e4-7d85-49f6-b233-1a5e2da3d542)

https://github.com/delta-io/delta/pull/1525#discussion_r1439882382
![image](https://github.com/delta-io/delta/assets/1336227/9c924af4-5350-4000-a84f-38fd33f8a7d0)

**Comment by kmate** [comment]
@felipepessoto I see that there's an attempt for #1916 that is open since a while (> 6 months?): #3345. Could we add that to the above table?

Also, if nobody is working on 5, I might take a stab at it; I'm just afraid a bit that I might conflict with the above mentioned open PR slightly.

**Comment by foss-contributor** [comment]
@felipepessoto, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!

**Comment by felipepessoto** [comment]
This issue is still valid
