### ISSUE TITLE
[Feature Request] Support Coordinated Commits in Delta Kernel

### ISSUE THREAD

**Issue by EstherBear** [delta-io/delta#3406]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Overview

Support both coordinated commits read and write in Delta Kernel.

### Motivation

Today Delta Spark supports coordinated commits. Delta Kernel should also support it to align with Delta Spark.

### Project Plan

| ID | Task description | PRs | Status | Author |
|----|------------------|----|--------|--------|
| 1  | Add monotonic inCommitTimestamp | #3218, #3269, #3276, #3282, #3283, [prototype](https://github.com/delta-io/delta/pull/3262) | DONE | @EstherBear  |
| 2  | Improve inCommitTimestamp read [#3321](#3321) |  | TODO | @EstherBear  |
| 3  | Prototypes of coordinated commits support in kernel | #3333, #3355 | Done | @EstherBear  |
| 4  | Add coordinated commits interfaces and table properties | #3370 | DONE | @EstherBear  |
| 5  | Add default coordinated commits handler implementation | #3396 | In Progress | @EstherBear  |
| 6  | Add parsing support for coordinated commits Map type table properties | #3400 | In Progress | @EstherBear  |
| 7  | Add InMemoryCommitCoordinator for testing | #3377 | In Progress | @EstherBear  |
| 8  | Update the Kernel read with coordinated commits support | #3381 | In Progress | @EstherBear  |
| 9  | Update the Kernel write with coordinated commits support | #3390 | In Progress | @EstherBear  |
| 10  | Update the Kernel checkpoint with coordinated commits support |  | TODO | @EstherBear  |
| 11  | Update the coordinated commits to support downgrade in Kernel |  | TODO | @EstherBear  |
| 12  | Reuse CoordinatedCommitBuilder interface in Storage Module |  | TODO | @EstherBear  |

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by foss-contributor** [comment]
@EstherBear, thank you for your contribution! This issue has been inactive for over 18 months and will be closed in one week. To keep it open, please leave a comment on this issue or contact us in the `#contributors` channel on [Delta Lake Slack](https://go.delta.io/slack). We appreciate your involvement in Delta Lake!
