### ISSUE TITLE
[Feature Request][Spark] Add Row Tracking Backfill

### ISSUE THREAD

**Issue by longvu-db** [delta-io/delta#3450]
#### Which Delta project/connector is this regarding?

- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Overview

This feature tracks the implementation effort of [Backfill](https://docs.google.com/document/d/1ji3zIWURSz_qugpRHjIV_2BUZPVKxYMiEFaDORt_ULA/edit#heading=h.8al9qhd83yov).
### Motivation

Users will be able to enable Row Tracking on existing tables.
When Row Tracking is Enabled, Row IDs and Row Commit Versions are assigned automatically to the table rows. 

### Further details
- [Reading and Preserving Row Tracking information](https://github.com/delta-io/delta/issues/2111).
- [Row Commit Versions](https://github.com/delta-io/delta/issues/1715)
- [Row Commit Versions design doc](https://docs.google.com/document/d/1rODyxRE0BxDWGQHW8vyfV1PSGo7lE0D4ImNHJyygBbY/edit#heading=h.1vcrl76z8cnh)
- [Row IDs design doc](https://docs.google.com/document/d/1ji3zIWURSz_qugpRHjIV_2BUZPVKxYMiEFaDORt_ULA/edit#heading=h.8al9qhd83yov)
- [Row Tracking protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#row-tracking)

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [X] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by allisonport-db** [comment]
Closed in https://github.com/delta-io/delta/pull/3449
